name: RDP-VPS

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok & NSSM
      run: |
        Invoke-WebRequest https://drive.google.com/uc?id=1a5NuP95Kei1hGQNMSFqhNhc5oCQZbg50  -OutFile ngrok.exe
        Invoke-WebRequest https://drive.google.com/uc?id=1a8rAXV-4voo9wK6Nm-qaOleSFQyXUPtb  -OutFile nssm.exe
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Connect your NGROK account
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://drive.google.com/uc?id=1_pid-lkhY5o21fbxYXhMLhxuodbBvi-3  -OutFile NGROK-AP.bat
        Invoke-WebRequest https://drive.google.com/uc?id=1_q43MKisIDb-zicMSKmxf9yLx5utbPAd  -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://drive.google.com/uc?id=1_njRQ6Anmra7ZC8llxf-OpIG1hkADTAV  -OutFile loop.bat
    - name: Make YML file for NGROK.
      run: start NGROK-AP.bat
    - name: Enable RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel
      run: sc start ngrok
    - name: Connect to your RDP CPU 2 Core - 7GB Ram - 255 SSD.
      run: cmd /c NGROK-CHECK.bat
    - name: All Done! You can close Tab now! Maximum VM time:6h.
      run: cmd /c loop.bat
